from pathlib import Path
import os
import subprocess
import tempfile
import unittest


PARCEL = Path(__file__).resolve().parents[1] / "bin" / "parcel"


class HandoffTests(unittest.TestCase):
    def test_triple_quotes_do_not_break_snapshot_update(self):
        self.check_snapshot("Preserve triple quotes: '''")

    def test_backslashes_remain_literal(self):
        self.check_snapshot(r"Preserve C:\new\tools literally")

    def check_snapshot(self, message):
        with tempfile.TemporaryDirectory(prefix="parcel-test-") as directory:
            root = Path(directory)
            repo = root / "repo"
            repo.mkdir()
            targets = root / "config" / "targets"
            targets.mkdir(parents=True)
            (targets / "fixture.conf").write_text("HOST=fixture\nAGENT=claude\n")
            def git(*args):
                return subprocess.run(["git", *args], cwd=repo, check=True,
                                      capture_output=True, text=True)
            git("init", "-q")
            git("config", "user.name", "Parcel Test")
            git("config", "user.email", "parcel@example.invalid")
            git("-c", "commit.gpgsign=false", "commit", "--allow-empty", "-m", message)
            handoff = repo / "HANDOFF.md"
            handoff.write_text("# HANDOFF\n\nKeep this intent.\n\n## Machine state (auto-generated by parcel — do not edit)\nold snapshot\n")
            # Source via the harmless targets command, then replace every
            # transport/session operation before exercising the real send path.
            script = '''source "$1" targets >/dev/null
ssh() { printf '%s\\n' /tmp/parcel-fixture-target; }
rsync() { :; }
ship_claude() { RESUME_CMD=:; }
cmd_send fixture --idle
'''
            result = subprocess.run(["bash", "-c", script, "test", str(PARCEL)],
                                    cwd=repo, env={**os.environ, "PARCELS_HOME": str(root / "config")},
                                    capture_output=True, text=True)
            self.assertEqual(result.returncode, 0, result.stderr)
            body = handoff.read_text()
            self.assertIn("Keep this intent.", body)
            self.assertIn(message, body)
            self.assertNotIn("old snapshot", body)
            self.assertEqual(body.count("## Machine state"), 1)


if __name__ == "__main__":
    unittest.main()
